package co.dfns.sdk.auth.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum Network {
    Algorand("Algorand"),
    AlgorandTestnet("AlgorandTestnet"),
    Aptos("Aptos"),
    AptosTestnet("AptosTestnet"),
    ArbitrumOne("ArbitrumOne"),
    ArbitrumSepolia("ArbitrumSepolia"),
    ArcTestnet("ArcTestnet"),
    AvalancheC("AvalancheC"),
    AvalancheCFuji("AvalancheCFuji"),
    BabylonGenesis("BabylonGenesis"),
    BabylonTestnet5("BabylonTestnet5"),
    Base("Base"),
    BaseSepolia("BaseSepolia"),
    Berachain("Berachain"),
    BerachainBepolia("BerachainBepolia"),
    Bitcoin("Bitcoin"),
    BitcoinSignet("BitcoinSignet"),
    BitcoinTestnet3("BitcoinTestnet3"),
    BitcoinCash("BitcoinCash"),
    Bob("Bob"),
    BobSepolia("BobSepolia"),
    Bsc("Bsc"),
    BscTestnet("BscTestnet"),
    Canton("Canton"),
    CantonTestnet("CantonTestnet"),
    Cardano("Cardano"),
    CardanoPreprod("CardanoPreprod"),
    Concordium("Concordium"),
    ConcordiumTestnet("ConcordiumTestnet"),
    Celo("Celo"),
    CeloAlfajores("CeloAlfajores"),
    Codex("Codex"),
    CodexSepolia("CodexSepolia"),
    CosmosHub4("CosmosHub4"),
    CosmosIcsTestnet("CosmosIcsTestnet"),
    Dogecoin("Dogecoin"),
    DogecoinTestnet("DogecoinTestnet"),
    Ethereum("Ethereum"),
    EthereumClassic("EthereumClassic"),
    EthereumClassicMordor("EthereumClassicMordor"),
    EthereumSepolia("EthereumSepolia"),
    EthereumHolesky("EthereumHolesky"),
    EthereumHoodi("EthereumHoodi"),
    FantomOpera("FantomOpera"),
    FantomTestnet("FantomTestnet"),
    FlareC("FlareC"),
    FlareCCoston2("FlareCCoston2"),
    FlowEvm("FlowEvm"),
    FlowEvmTestnet("FlowEvmTestnet"),
    Hedera("Hedera"),
    HederaTestnet("HederaTestnet"),
    Ink("Ink"),
    InkSepolia("InkSepolia"),
    InternetComputer("InternetComputer"),
    Ion("Ion"),
    IonTestnet("IonTestnet"),
    Iota("Iota"),
    IotaTestnet("IotaTestnet"),
    Kaspa("Kaspa"),
    Kusama("Kusama"),
    KusamaAssetHub("KusamaAssetHub"),
    Litecoin("Litecoin"),
    LitecoinTestnet("LitecoinTestnet"),
    Near("Near"),
    NearTestnet("NearTestnet"),
    Optimism("Optimism"),
    OptimismSepolia("OptimismSepolia"),
    Origyn("Origyn"),
    Plasma("Plasma"),
    PlasmaTestnet("PlasmaTestnet"),
    Plume("Plume"),
    PlumeSepolia("PlumeSepolia"),
    Paseo("Paseo"),
    PaseoAssetHub("PaseoAssetHub"),
    Polkadot("Polkadot"),
    PolkadotAssetHub("PolkadotAssetHub"),
    Polygon("Polygon"),
    PolygonAmoy("PolygonAmoy"),
    Polymesh("Polymesh"),
    PolymeshTestnet("PolymeshTestnet"),
    Race("Race"),
    RaceSepolia("RaceSepolia"),
    SeiAtlantic2("SeiAtlantic2"),
    SeiPacific1("SeiPacific1"),
    Solana("Solana"),
    SolanaDevnet("SolanaDevnet"),
    Starknet("Starknet"),
    StarknetSepolia("StarknetSepolia"),
    Stellar("Stellar"),
    StellarTestnet("StellarTestnet"),
    Sui("Sui"),
    SuiTestnet("SuiTestnet"),
    Tezos("Tezos"),
    TezosGhostnet("TezosGhostnet"),
    Tempo("Tempo"),
    TempoModerato("TempoModerato"),
    Tsc("Tsc"),
    TscTestnet1("TscTestnet1"),
    Ton("Ton"),
    TonTestnet("TonTestnet"),
    Tron("Tron"),
    TronNile("TronNile"),
    Westend("Westend"),
    WestendAssetHub("WestendAssetHub"),
    XrpLedger("XrpLedger"),
    XrpLedgerTestnet("XrpLedgerTestnet"),
    UNKNOWN(null);


    private final String value;

    Network(String value) { this.value = value; }

    @JsonValue
    public String getValue() { return value; }

    @JsonCreator
    public static Network fromValue(String value) {
        for (Network e : values()) {
            if (e.value != null && e.value.equals(value)) return e;
        }
        return UNKNOWN;
    }
}
