package co.dfns.sdk.exchanges;

import co.dfns.sdk.DfnsClientConfig;
import co.dfns.sdk.exchanges.model.CreateDepositResponse;
import co.dfns.sdk.internal.DfnsHttpClient;
import com.sun.net.httpserver.HttpServer;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.lang.reflect.Method;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CopyOnWriteArrayList;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Repo-owned test that the {@code @Deprecated} forwarding alias generated by the
 * operationId rename issues the exact same HTTP request as its canonical method.
 *
 * <p>Endpoint under test: exchanges "create deposit" — canonical {@code createDeposit}
 * with deprecated alias {@code createExchangeDeposit}. A "new"-decision row: a POST with
 * a typed body, so we assert method + path + body forwarding, not just the method name.
 *
 * <p>Uses the JDK's built-in {@link HttpServer} as a stub API (same approach as
 * {@code DfnsHttpClientCoreTest}), so there are no external test dependencies. The client
 * is configured without a Signer, so each call issues a single direct POST (no user-action
 * challenge round-trip), which is exactly the request we want to compare.
 */
class DeprecatedAliasTest {

    private record Recorded(String method, String path, String body) {}

    /** A stub API that records every request it receives and replies with a fixed JSON body. */
    private static final class StubServer implements AutoCloseable {
        final HttpServer server;
        final List<Recorded> requests = new CopyOnWriteArrayList<>();

        StubServer(String responseBody) throws IOException {
            server = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
            server.createContext("/", exchange -> {
                byte[] req = exchange.getRequestBody().readAllBytes();
                requests.add(new Recorded(
                    exchange.getRequestMethod(),
                    exchange.getRequestURI().getPath(),
                    new String(req, StandardCharsets.UTF_8)));
                byte[] resp = responseBody.getBytes(StandardCharsets.UTF_8);
                exchange.getResponseHeaders().add("Content-Type", "application/json");
                exchange.sendResponseHeaders(200, resp.length);
                exchange.getResponseBody().write(resp);
                exchange.close();
            });
            server.start();
        }

        String baseUrl() {
            return "http://127.0.0.1:" + server.getAddress().getPort();
        }

        @Override
        public void close() {
            server.stop(0);
        }
    }

    private ExchangesClient clientFor(StubServer s) {
        DfnsClientConfig config = DfnsClientConfig.builder()
            .baseUrl(s.baseUrl())
            .authToken("test-token")
            .build();
        return new ExchangesClient(new DfnsHttpClient(config));
    }

    @Test
    void deprecatedAliasAndCanonicalMethodBothExist() throws NoSuchMethodException {
        Method canonical = ExchangesClient.class.getMethod(
            "createDeposit", String.class, String.class, Object.class);
        Method deprecated = ExchangesClient.class.getMethod(
            "createExchangeDeposit", String.class, String.class, Object.class);

        assertTrue(deprecated.isAnnotationPresent(Deprecated.class),
            "createExchangeDeposit must carry @Deprecated");
        // Same return type — the alias is a thin forwarder, not a distinct endpoint.
        assertEquals(canonical.getReturnType(), deprecated.getReturnType());
    }

    @Test
    void deprecatedAliasForwardsToSameRequestAsCanonical() throws Exception {
        String responseBody = "{\"id\":\"dp-1\",\"exchangeId\":\"ex-1\",\"accountId\":\"acc-1\","
            + "\"kind\":\"Native\",\"walletId\":\"wa-1\",\"dateCreated\":\"2026-01-01T00:00:00Z\"}";

        try (StubServer s = new StubServer(responseBody)) {
            ExchangesClient client = clientFor(s);
            Object body = Map.of("kind", "Native", "asset", "ETH", "amount", "1.5");

            // Canonical call
            CreateDepositResponse viaCanonical = client.createDeposit("ex-1", "acc-1", body);
            // Deprecated alias call — should forward to the very same endpoint
            @SuppressWarnings("deprecation")
            CreateDepositResponse viaAlias = client.createExchangeDeposit("ex-1", "acc-1", body);

            assertEquals("dp-1", viaCanonical.id());
            assertEquals("dp-1", viaAlias.id());

            assertEquals(2, s.requests.size(), "expected exactly one request per call");
            Recorded canonicalReq = s.requests.get(0);
            Recorded aliasReq = s.requests.get(1);

            String expectedPath = "/exchanges/ex-1/accounts/acc-1/deposits";
            assertEquals("POST", canonicalReq.method());
            assertEquals(expectedPath, canonicalReq.path());

            // The alias must issue an identical request: same method, path, and body.
            assertEquals(canonicalReq.method(), aliasReq.method());
            assertEquals(canonicalReq.path(), aliasReq.path());
            assertEquals(canonicalReq.body(), aliasReq.body());

            // Sanity: the typed body really was forwarded on the wire.
            assertTrue(aliasReq.body().contains("\"asset\":\"ETH\""), aliasReq.body());
        }
    }
}
